<style>
body h1:before, body h2:before, body h3:before, body h4:before, body h5:before, body h6:before {
  content: "";
  counter-increment: none;
}
</style>

# Week07.2 Team Activity
Due Thursday May 18th, 2023 by 11:59pm - please upload PDF with photograph (either rendered or a separate file).  There is no expectation of completing this during class, in fact, I am trying to get you to practice working outside of class in teams in preparation for the final project.

If you missed class – no credit for this activity, instead, I drop two unexcused absences from the Monday/Wednesday activities before deductions begin.

- **Please identify your team & the names of your teammates.** 

- **Please insert a team photo somewhere in this notebook.  If you cannot get the to render correctly to PDF please upload a separate file of the photo**

- **Please make certain that all of your teammates agree upon and understand the team answers. Thank you.**



Names: Blair L, Aryan S, Ryan T

In [11]:
from IPython.display import Image
Image(".jpeg")

## Assignment

 

As always, what is important is a team effort and that everyone on the team has an idea of how to program these things and also feels free to ask the team for more understanding.  

Because we are in the process of forming final teams, if you are having trouble coming together as a team to complete an assignment like this one,  you should look for a different team for the next activity.

## Mash-Up Maybe...

Today's team activity involves using some things we've learned about in the past (strings, removing duplicates) and from Numpy today (creating matrices.

In [19]:
import numpy as np
import requests

url = 'http://www.stat.ucla.edu/~vlew/datasets/die_for_you.txt'

response = requests.get(url)

# .text is a property of the Response object
# .lower is a string method
ex_text = response.text.lower()

punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

# please remove the punctuation as seen in punc
no_punc = []
no_punc_ex_text = []
for letter in ex_text:
    if letter not in punc:
        no_punc.append(letter)
        no_punc_ex_text = "".join(no_punc)
ex_text = no_punc_ex_text
 
print(ex_text[0:255])

im findin ways to articulate the feelin im goin through
i just cant say i dont love you yeah
cause i love you yeah
its hard for me to communicate the thoughts that i hold
but tonight im gon let you know
let me tell the truth
baby let me tell the truth yea


In [32]:
# split ex_text into separate words save as a list (you will need this later)
words = ex_text.split()

# remove the duplicate words (heard that before?) save as a different list
vocab = []
for word in words:
    if word not in vocab:
        vocab.append(word)

print(vocab)

# check the length of the non duplicated word list
print(len(vocab))
# 113

['im', 'findin', 'ways', 'to', 'articulate', 'the', 'feelin', 'goin', 'through', 'i', 'just', 'cant', 'say', 'dont', 'love', 'you', 'yeah', 'cause', 'its', 'hard', 'for', 'me', 'communicate', 'thoughts', 'that', 'hold', 'but', 'tonight', 'gon', 'let', 'know', 'tell', 'truth', 'baby', 'what', 'thinkin', 'see', 'it', 'in', 'your', 'eyes', 'hate', 'want', 'when', 'cry', 'youre', 'scared', 'be', 'lonely', 'specially', 'night', 'ill', 'miss', 'happens', 'every', 'time', 'this', 'afford', 'try', 'find', 'a', 'reason', 'pull', 'us', 'apart', 'aint', 'workin', 'perfect', 'and', 'worth', 'walk', 'away', 'oh', 'even', 'though', 'were', 'makes', 'feel', 'alone', 'would', 'die', 'distance', 'between', 'itll', 'never', 'change', 'my', 'mind', 'manipulate', 'girl', 'not', 'blamin', 'blame', 'too', 'take', 'pain', 'forever', 'wont', 'no', 'one', 'thats', 'better', 'right', 'babe', 'think', 'uh', 'lie', 'keep', 'real', 'with', 'kill', 'sayin', 'nanana']
113


In [39]:
# create a square matrix of zeros using the length of 
# the non-duplicated words for the length of rows, cols
matrix = np.zeros((len(vocab), len(vocab)))
print(matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [40]:
# use the .shape attribute to show it's correct
matrix.shape

(113, 113)

## The Next Step

(programmed for you) A transition matrix (typically used for Markov Chains) serving as a small step to illustrate some of the concepts involved in Large Language Models.

If you think of each unique word in any text as a "state", a Markov Chain can generate text by starting at a certain word and then randomly choosing the next word based on the probabilities in the transition matrix.

This is much simpler than a language model, especially like ChatGPT. Models like that not only look at the next word, but it also looks at the context of a sentence or a paragraph to predict the next word or to generate text.

In [41]:
# fill the matrix with transition probabilities
# did it for you, feel free to correct any errors...
# assuming your duplicated list of words without punctuation is named words
# assuming your non-duplicated version is named vocab

for i in range(len(words) - 1):
    current_word = words[i]
    next_word = words[i + 1]

    current_index = vocab.index(current_word)
    next_index = vocab.index(next_word)

    matrix[current_index][next_index] += 1

# normalize the matrix rows to sum to 1
row_sums = matrix.sum(axis=1, keepdims=True)

# Avoid division by zero
matrix = np.where(row_sums != 0, matrix / row_sums, matrix)
matrix

array([[0.        , 0.18181818, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.66666667]])

## Try it out

If everything is working, generated_text should be a random word from vocab (which is your non-duplicated word list)

In [51]:
# assuming your non-duplicated list of words is named vocab
# generate text
generated_text = [np.random.choice(vocab)]
generated_text

['tell']

# Choose an integer for num_words

This is the length of the string you wish to generate. These words are generated probabilistically.

In [52]:
num_words = 9

for i in range(num_words):
    last_word = generated_text[-1]
    last_index = vocab.index(last_word)

    next_word = np.random.choice(vocab, p=matrix[last_index])
    generated_text.append(next_word)

print(" ".join(generated_text))

tell the distance and the time between us apart it


## What to submit for credit

- Please upload the Jupyter Notebook (.ipynb) and PDF (preferred) OR .html (OK) to Bruin Learn with your team attempt.  Please make sure every team member understands the contents of the notebook.  

- This is due before 11:59pm Thursday 5/18/2023 